### ISSUE TITLE
Thavnairan Striking dummy can't be clicked

### ISSUE THREAD

**Issue by Tatsu941** [Sevii77/properhousing#1]
Hey,
quick thing I found that outside you can't click the Thavnairan Striking dummy, once it is place, with the plugin on

thanks and regards

**Comment by Tatsu941** [comment]
chocobo stable aswell

**Comment by Sevii77** [comment]
I've temporarily disabled funtionality outdoors due to a bigger issue which is the cause of this. I'll reenable it once I find a good solution.

**Comment by Tatsu941** [comment]
> 

ok thank you! (It is not as needed outside anyway but I am really thankful having it indoors)
